import type { Bookmark } from "@/types/bookmark";

export const bookmarks: Bookmark[] = [
  {
    name: "OpenAI Platform",
    href: "https://platform.openai.com",
    note: "模型、API、控制台与开发文档",
    category: "AI Tools",
    tone: "模型",
  },
  {
    name: "ChatGPT",
    href: "https://chatgpt.com",
    note: "日常协作、研究与灵感整理",
    category: "AI Tools",
    tone: "助手",
  },
  {
    name: "Claude",
    href: "https://claude.ai",
    note: "长文本、代码与知识处理",
    category: "AI Tools",
    tone: "写作",
  },
  {
    name: "Cursor",
    href: "https://cursor.com",
    note: "AI 编程编辑器与项目开发",
    category: "Agent",
    tone: "IDE",
  },
  {
    name: "LangChain",
    href: "https://www.langchain.com",
    note: "Agent 编排、工具调用与应用框架",
    category: "Agent",
    tone: "框架",
  },
  {
    name: "CrewAI",
    href: "https://www.crewai.com",
    note: "多 Agent 工作流与自动化实验",
    category: "Agent",
    tone: "协作",
  },
  {
    name: "n8n",
    href: "https://n8n.io",
    note: "自动化流程编排、Webhook 与集成任务",
    category: "Workflow",
    tone: "自动化",
  },
  {
    name: "Dify",
    href: "https://dify.ai",
    note: "AI 应用、Agent 与工作流构建平台",
    category: "Workflow",
    tone: "编排",
  },
  {
    name: "GitHub Actions",
    href: "https://github.com/features/actions",
    note: "代码仓库中的 CI/CD 与自动任务",
    category: "Workflow",
    tone: "CI/CD",
  },
  {
    name: "Python",
    href: "https://www.python.org",
    note: "语言官网、版本下载与文档入口",
    category: "Python",
    tone: "语言",
  },
  {
    name: "PyPI",
    href: "https://pypi.org",
    note: "Python 包检索与依赖查阅",
    category: "Python",
    tone: "包",
  },
  {
    name: "FastAPI",
    href: "https://fastapi.tiangolo.com",
    note: "高性能 API 服务开发框架",
    category: "Python",
    tone: "后端",
  },
  {
    name: "GSAP",
    href: "https://gsap.com",
    note: "高级网页动效与时间线动画",
    category: "动画",
    tone: "动效",
  },
  {
    name: "Framer Motion",
    href: "https://motion.dev",
    note: "React 动画、手势与布局过渡",
    category: "动画",
    tone: "React",
  },
  {
    name: "LottieFiles",
    href: "https://lottiefiles.com",
    note: "轻量动画资源、预览与导出",
    category: "动画",
    tone: "素材",
  },
];
